version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend.dockerfile
    working_dir: /front-end
    ports:
      - "3000:3000"
    volumes:
      - ./front-end:/front-end
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: backend.dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "80:80"
    environment:
      - ENV=development
