@extends('components.layouts.Base') 

@section('title', 'Hra')

@section('content')
<table id="tictactoe-board">
    <tbody>
        <tr>
            <td>{{$game->board[0][0]}}</td>
            <td>{{$game->board[0][1]}}</td>
            <td>{{$game->board[0][2]}}</td>
            <td>{{$game->board[0][3]}}</td>
            <td>{{$game->board[0][4]}}</td>
            <td>{{$game->board[0][5]}}</td>
            <td>{{$game->board[0][6]}}</td>
            <td>{{$game->board[0][7]}}</td>
            <td>{{$game->board[0][8]}}</td>
            <td>{{$game->board[0][9]}}</td>
            <td>{{$game->board[0][10]}}</td>
            <td>{{$game->board[0][11]}}</td>
            <td>{{$game->board[0][12]}}</td>
            <td>{{$game->board[0][13]}}</td>
            <td>{{$game->board[0][14]}}</td>
        </tr>
        <tr>
            <td>{{$game->board[1][0]}}</td>
            <td>{{$game->board[1][1]}}</td>
            <td>{{$game->board[1][2]}}</td>
            <td>{{$game->board[1][3]}}</td>
            <td>{{$game->board[1][4]}}</td>
            <td>{{$game->board[1][5]}}</td>
            <td>{{$game->board[1][6]}}</td>
            <td>{{$game->board[1][7]}}</td>
            <td>{{$game->board[1][8]}}</td>
            <td>{{$game->board[1][9]}}</td>
            <td>{{$game->board[1][10]}}</td>
            <td>{{$game->board[1][11]}}</td>
            <td>{{$game->board[1][12]}}</td>
            <td>{{$game->board[1][13]}}</td>
            <td>{{$game->board[1][14]}}</td>
        </tr>
        <tr>
            <td>{{$game->board[2][0]}}</td>
            <td>{{$game->board[2][1]}}</td>
            <td>{{$game->board[2][2]}}</td>
            <td>{{$game->board[2][3]}}</td>
            <td>{{$game->board[2][4]}}</td>
            <td>{{$game->board[2][5]}}</td>
            <td>{{$game->board[2][6]}}</td>
            <td>{{$game->board[2][7]}}</td>
            <td>{{$game->board[2][8]}}</td>
            <td>{{$game->board[2][9]}}</td>
            <td>{{$game->board[2][10]}}</td>
            <td>{{$game->board[2][11]}}</td>
            <td>{{$game->board[2][12]}}</td>
            <td>{{$game->board[2][13]}}</td>
            <td>{{$game->board[2][14]}}</td>
        </tr>
        <tr>
            <td>{{$game->board[3][0]}}</td>
            <td>{{$game->board[3][1]}}</td>
            <td>{{$game->board[3][2]}}</td>
            <td>{{$game->board[3][3]}}</td>
            <td>{{$game->board[3][4]}}</td>
            <td>{{$game->board[3][5]}}</td>
            <td>{{$game->board[3][6]}}</td>
            <td>{{$game->board[3][7]}}</td>
            <td>{{$game->board[3][8]}}</td>
            <td>{{$game->board[3][9]}}</td>
            <td>{{$game->board[3][10]}}</td>
            <td>{{$game->board[3][11]}}</td>
            <td>{{$game->board[3][12]}}</td>
            <td>{{$game->board[3][13]}}</td>
            <td>{{$game->board[3][14]}}</td>
        </tr>
        <tr>
            <td>{{$game->board[4][0]}}</td>
            <td>{{$game->board[4][1]}}</td>
            <td>{{$game->board[4][2]}}</td>
            <td>{{$game->board[4][3]}}</td>
            <td>{{$game->board[4][4]}}</td>
            <td>{{$game->board[4][5]}}</td>
            <td>{{$game->board[4][6]}}</td>
            <td>{{$game->board[4][7]}}</td>
            <td>{{$game->board[4][8]}}</td>
            <td>{{$game->board[4][9]}}</td>
            <td>{{$game->board[4][10]}}</td>
            <td>{{$game->board[4][11]}}</td>
            <td>{{$game->board[4][12]}}</td>
            <td>{{$game->board[4][13]}}</td>
            <td>{{$game->board[4][14]}}</td>
        </tr>
        <tr>
            <td>{{$game->board[5][0]}}</td>
            <td>{{$game->board[5][1]}}</td>
            <td>{{$game->board[5][2]}}</td>
            <td>{{$game->board[5][3]}}</td>
            <td>{{$game->board[5][4]}}</td>
            <td>{{$game->board[5][5]}}</td>
            <td>{{$game->board[5][6]}}</td>
            <td>{{$game->board[5][7]}}</td>
            <td>{{$game->board[5][8]}}</td>
            <td>{{$game->board[5][9]}}</td>
            <td>{{$game->board[5][10]}}</td>
            <td>{{$game->board[5][11]}}</td>
            <td>{{$game->board[5][12]}}</td>
            <td>{{$game->board[5][13]}}</td>
            <td>{{$game->board[5][14]}}</td>
        </tr>
        <tr>
            <td>{{$game->board[6][0]}}</td>
            <td>{{$game->board[6][1]}}</td>
            <td>{{$game->board[6][2]}}</td>
            <td>{{$game->board[6][3]}}</td>
            <td>{{$game->board[6][4]}}</td>
            <td>{{$game->board[6][5]}}</td>
            <td>{{$game->board[6][6]}}</td>
            <td>{{$game->board[6][7]}}</td>
            <td>{{$game->board[6][8]}}</td>
            <td>{{$game->board[6][9]}}</td>
            <td>{{$game->board[6][10]}}</td>
            <td>{{$game->board[6][11]}}</td>
            <td>{{$game->board[6][12]}}</td>
            <td>{{$game->board[6][13]}}</td>
            <td>{{$game->board[6][14]}}</td>
        </tr>
        <tr>
            <td>{{$game->board[7][0]}}</td>
            <td>{{$game->board[7][1]}}</td>
            <td>{{$game->board[7][2]}}</td>
            <td>{{$game->board[7][3]}}</td>
            <td>{{$game->board[7][4]}}</td>
            <td>{{$game->board[7][5]}}</td>
            <td>{{$game->board[7][6]}}</td>
            <td>{{$game->board[7][7]}}</td>
            <td>{{$game->board[7][8]}}</td>
            <td>{{$game->board[7][9]}}</td>
            <td>{{$game->board[7][10]}}</td>
            <td>{{$game->board[7][11]}}</td>
            <td>{{$game->board[7][12]}}</td>
            <td>{{$game->board[7][13]}}</td>
            <td>{{$game->board[7][14]}}</td>
        </tr>
        <tr>
            <td>{{$game->board[8][0]}}</td>
            <td>{{$game->board[8][1]}}</td>
            <td>{{$game->board[8][2]}}</td>
            <td>{{$game->board[8][3]}}</td>
            <td>{{$game->board[8][4]}}</td>
            <td>{{$game->board[8][5]}}</td>
            <td>{{$game->board[8][6]}}</td>
            <td>{{$game->board[8][7]}}</td>
            <td>{{$game->board[8][8]}}</td>
            <td>{{$game->board[8][9]}}</td>
            <td>{{$game->board[8][10]}}</td>
            <td>{{$game->board[8][11]}}</td>
            <td>{{$game->board[8][12]}}</td>            
            <td>{{$game->board[8][13]}}</td>
            <td>{{$game->board[8][14]}}</td>
        </tr>
        <tr>
            <td>{{$game->board[9][0]}}</td>
            <td>{{$game->board[9][1]}}</td>
            <td>{{$game->board[9][2]}}</td>
            <td>{{$game->board[9][3]}}</td>
            <td>{{$game->board[9][4]}}</td>
            <td>{{$game->board[9][5]}}</td>
            <td>{{$game->board[9][6]}}</td>
            <td>{{$game->board[9][7]}}</td>
            <td>{{$game->board[9][8]}}</td>
            <td>{{$game->board[9][9]}}</td>
            <td>{{$game->board[9][10]}}</td>
            <td>{{$game->board[9][11]}}</td>
            <td>{{$game->board[9][12]}}</td>
            <td>{{$game->board[9][13]}}</td>
            <td>{{$game->board[9][14]}}</td>
        </tr>
        <tr>
            <td>{{$game->board[10][0]}}</td>
            <td>{{$game->board[10][1]}}</td>
            <td>{{$game->board[10][2]}}</td>
            <td>{{$game->board[10][3]}}</td>
            <td>{{$game->board[10][4]}}</td>
            <td>{{$game->board[10][5]}}</td>
            <td>{{$game->board[10][6]}}</td>
            <td>{{$game->board[10][7]}}</td>
            <td>{{$game->board[10][8]}}</td>
            <td>{{$game->board[10][9]}}</td>
            <td>{{$game->board[10][10]}}</td>
            <td>{{$game->board[10][11]}}</td>
            <td>{{$game->board[10][12]}}</td>
            <td>{{$game->board[10][13]}}</td>
            <td>{{$game->board[10][14]}}</td>
        </tr>
        <tr>
            <td>{{$game->board[11][0]}}</td>
            <td>{{$game->board[11][1]}}</td>
            <td>{{$game->board[11][2]}}</td>
            <td>{{$game->board[11][3]}}</td>
            <td>{{$game->board[11][4]}}</td>
            <td>{{$game->board[11][5]}}</td>
            <td>{{$game->board[11][6]}}</td>
            <td>{{$game->board[11][7]}}</td>
            <td>{{$game->board[11][8]}}</td>
            <td>{{$game->board[11][9]}}</td>
            <td>{{$game->board[11][10]}}</td>
            <td>{{$game->board[11][11]}}</td>
            <td>{{$game->board[11][12]}}</td>
            <td>{{$game->board[11][13]}}</td>
            <td>{{$game->board[11][14]}}</td>
        </tr>
        <tr>
            <td>{{$game->board[12][0]}}</td>
            <td>{{$game->board[12][1]}}</td>
            <td>{{$game->board[12][2]}}</td>
            <td>{{$game->board[12][3]}}</td>
            <td>{{$game->board[12][4]}}</td>
            <td>{{$game->board[12][5]}}</td>
            <td>{{$game->board[12][6]}}</td>
            <td>{{$game->board[12][7]}}</td>
            <td>{{$game->board[12][8]}}</td>
            <td>{{$game->board[12][9]}}</td>
            <td>{{$game->board[12][10]}}</td>
            <td>{{$game->board[12][11]}}</td>
            <td>{{$game->board[12][12]}}</td>
            <td>{{$game->board[12][13]}}</td>
            <td>{{$game->board[12][14]}}</td>
        </tr>
        <tr>
            <td>{{$game->board[13][0]}}</td>
            <td>{{$game->board[13][1]}}</td>
            <td>{{$game->board[13][2]}}</td>
            <td>{{$game->board[13][3]}}</td>
            <td>{{$game->board[13][4]}}</td>
            <td>{{$game->board[13][5]}}</td>
            <td>{{$game->board[13][6]}}</td>
            <td>{{$game->board[13][7]}}</td>
            <td>{{$game->board[13][8]}}</td>
            <td>{{$game->board[13][9]}}</td>
            <td>{{$game->board[13][10]}}</td>
            <td>{{$game->board[13][11]}}</td>
            <td>{{$game->board[13][12]}}</td>
            <td>{{$game->board[13][13]}}</td>
            <td>{{$game->board[13][14]}}</td>
        </tr>
        <tr>
            <td>{{$game->board[14][0]}}</td>
            <td>{{$game->board[14][1]}}</td>
            <td>{{$game->board[14][2]}}</td>
            <td>{{$game->board[14][3]}}</td>
            <td>{{$game->board[14][4]}}</td>
            <td>{{$game->board[14][5]}}</td>
            <td>{{$game->board[14][6]}}</td>
            <td>{{$game->board[14][7]}}</td>
            <td>{{$game->board[14][8]}}</td>
            <td>{{$game->board[14][9]}}</td>
            <td>{{$game->board[14][10]}}</td>
            <td>{{$game->board[14][11]}}</td>
            <td>{{$game->board[14][12]}}</td>
            <td>{{$game->board[14][13]}}</td>
            <td>{{$game->board[14][14]}}</td>
        </tr>
    </tbody>
</table>

@endsection
